# main text of home
name: Rodolfo Ferro
bio: "Let's build our future. 🚀"

# twitter summary info
description: "💻 Dev @Bisonic_Games • 🧠 ML + Blockchain + Back Engineer • 🐍 Pythonista • 🚀 @futurelabmx co-founder • 👨🏻‍💻 prev @ploomber @CodeandoMexico @Innovacion_Leon"

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/rodo_2021.png

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: resume

url: https://rodolfoferro.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: rodolfoferro-github-io # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
twitter: rodo_ferro
instagram: rodo_ferro
github: RodolfoFerro
linkedin: rodolfoferro
email: rodolfoferroperez@gmail.com
# youtube: channel/UC3Q7iZXB950Bvtjpml9jqZg
# medium: rodolfoferro
# google: 
# pinterest: mypinterest
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# vimeo: myvimeo
# lanyrd: mylanyrd

authors:
    rodferro:
        name: Rodolfo Ferro
        bio: With great power comes great responsibility.
        external-image: false
        picture: assets/images/profile.jpg
        twitter: rodo_ferro

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-admin

jekyll-mentions:
    base_url: ''
